import { Routes } from '@angular/router';
import { FeaturePlugin } from '@content-lab/plugin-system';
import featureConfig from '../feature.config.js';
import type { FeatureConfig } from './core/plugin-system/feature-config.interface';

/**
 * 🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by: scripts/generate-routes.js
 * Generated from: apps/content-lab/src/feature.config.js
 * Plugins discovered via: Convention-based discovery (Phase 3)
 *
 * Changes made here will be overwritten on next build.
 * To modify routes, edit feature.config.js and run: npm run generate:routes
 *
 * Phase 3: Plugins are now auto-discovered from features/ directory
 * No manual registration needed - just create the plugin file!
 *
 * See docs/PLUGIN_DEVELOPMENT_GUIDE.md for workflow details
 */

// Import enabled plugin metadata (generated based on feature configuration)
import { plugin as markdownToHtmlPlugin } from './features/markdown-to-html/markdown-to-html.plugin';
import { plugin as textEditorPlugin } from './features/text-editor/text-editor.plugin';
import { plugin as svgEditorPlugin } from './features/svg-editor/svg-editor.plugin';
import { plugin as jsPlaygroundPlugin } from './features/js-playground/js-playground.plugin';
import { plugin as jsonEditorPlugin } from './features/json-editor/json-editor.plugin';
import { plugin as regexTesterPlugin } from './features/regex-tester/regex-tester.plugin';
import { plugin as diffCheckerPlugin } from './features/diff-checker/diff-checker.plugin';
import { plugin as csvEditorPlugin } from './features/csv-editor/csv-editor.plugin';
import { plugin as wordCounterPlugin } from './features/word-counter/word-counter.plugin';
import { plugin as base64EncoderPlugin } from './features/base64-encoder/base64-encoder.plugin';
import { plugin as worldClockPlugin } from './features/world-clock/world-clock.plugin';
import { plugin as flacPlayerPlugin } from './features/flac-player/flac-player.plugin';
import { plugin as timelineVisualizerPlugin } from './features/timeline-visualizer/timeline-visualizer.plugin';
import { plugin as globeVisualizerPlugin } from './features/globe-visualizer/globe-visualizer.plugin';
import { plugin as starMapPlugin } from './features/star-map/star-map.plugin';
import { plugin as tetrisPlugin } from './features/tetris/tetris.plugin';
import { plugin as epubToPdfPlugin } from './features/epub-to-pdf/epub-to-pdf.plugin';
import { plugin as apiTesterPlugin } from './features/api-tester/api-tester.plugin';

/**
 * Map of enabled plugins by feature ID
 * Only features enabled in feature.config.ts are imported
 */
const allPlugins: Record<string, FeaturePlugin> = {
  'markdown-to-html': markdownToHtmlPlugin,
  'text-editor': textEditorPlugin,
  'svg-editor': svgEditorPlugin,
  'js-playground': jsPlaygroundPlugin,
  'json-editor': jsonEditorPlugin,
  'regex-tester': regexTesterPlugin,
  'diff-checker': diffCheckerPlugin,
  'csv-editor': csvEditorPlugin,
  'word-counter': wordCounterPlugin,
  'base64-encoder': base64EncoderPlugin,
  'world-clock': worldClockPlugin,
  'flac-player': flacPlayerPlugin,
  'timeline-visualizer': timelineVisualizerPlugin,
  'globe-visualizer': globeVisualizerPlugin,
  'star-map': starMapPlugin,
  'tetris': tetrisPlugin,
  'epub-to-pdf': epubToPdfPlugin,
  'api-tester': apiTesterPlugin
};

/**
 * Features that should be preloaded for better UX
 */
const preloadFeatures = new Set([
  'markdown-to-html',
  'text-editor',
  'world-clock'
]);

/**
 * Dynamically generate routes from enabled plugins
 */
function generateRoutes(): Routes {
  const pluginRoutes: Routes = [];

  // Get enabled features from configuration
  const enabledFeatures = Object.entries(featureConfig.features)
    .filter(([_, config]: [string, FeatureConfig]) => config.enabled)
    .map(([featureId, _]) => featureId);

  console.log(`[Routes] Generating routes for ${enabledFeatures.length} enabled features`);

  // Generate route for each enabled plugin
  for (const featureId of enabledFeatures) {
    const plugin = allPlugins[featureId];

    if (!plugin) {
      console.warn(`[Routes] Plugin not found for feature: ${featureId}`);
      continue;
    }

    // Remove leading slash if present to avoid double slashes
    const path = plugin.metadata.route.startsWith('/')
      ? plugin.metadata.route.substring(1)
      : plugin.metadata.route;

    pluginRoutes.push({
      path: path,
      loadComponent: plugin.loadComponent,
      data: {
        preload: preloadFeatures.has(featureId),
        pluginId: featureId,
        pluginName: plugin.metadata.name
      }
    });
  }

  return [
    // Default redirect to first enabled feature (or markdown-to-html as fallback)
    {
      path: '',
      redirectTo: pluginRoutes.length > 0
        ? pluginRoutes[0].path
        : 'tools/md-html',
      pathMatch: 'full'
    },
    // All plugin routes
    ...pluginRoutes,
    // Catch-all redirect
    {
      path: '**',
      redirectTo: pluginRoutes.length > 0
        ? pluginRoutes[0].path
        : 'tools/md-html'
    }
  ];
}

export const routes: Routes = generateRoutes();
